package responses

const (
	OK                           = "SUCCESS"
	DOMAIN_EXCEPTION             = "DOMAIN_EXCEPTION"
	NOT_FOUND_EXCEPTION          = "NOT_FOUND"
	UNEXPECTED_EXCEPTION         = "UNHANDLED_EXCEPTION"
	REQUEST_VALIDATION_EXCEPTION = "REQUEST_VALIDATION_EXCEPTION"
	UNAUTHORIZED_REQUEST         = "UNAUTHORIZED"
	REQUIRES_CREDENTIALS         = "MISSING_CREDENTIALS"
	INVALID_CREDENTIALS          = "INVALID_CREDENTIALS"
	INVALID_ACCESS               = "INVALID_ACCESS"
	CONCURRENCY_EXCEPTION        = "CONCURRENCY_EXCEPTION"
	DOWNSTREAM_EXCEPTION         = "DOWNSTREAM_EXCEPTION"
	UNSUPPORTED_CONTENT          = "UNSUPPORTED_CONTENT"
)
